version: "3.8"

services:
  frontend:
    container_name: bookstore_client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    image: mariosandovall/bookstore_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/
    environment:
      REACT_APP_API: "http://localhost:5000"
  backend:
    container_name: bookstore_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: mariosandovall/bookstore_server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/
    depends_on:
      - db
    environment:
      PORT: 5000
      MONGO_URL: "mongodb://db:27017/bookstore"
  db:
    container_name: db
    image: mongo
    volumes:
      - /data/db
